### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by DigNZ** [dreamfactorysoftware/dsp-core#101]
I'm installing on CentOS following this guide:

https://github.com/dreamfactorysoftware/dsp-core/wiki/Install-CentOS-RedHat

I get it running and enter my details to make an admin account.  I then get the product support question, whichever solution I chose I get an error:

Error 500
Internal Server Error

Error Details
Trying to get property of non-object

Part of the stacktrace here (its huge):

```
Array
(
    [_viewFile_] => /opt/dreamfactory/platform/app/views/web/error.php
    [_data_] => Array
        (
            [current_user] => CWebUser Object
                (
                    [allowAutoLogin] => 1
                    [guestName] => Guest
                    [loginUrl] => Array
                        (
                            [0] => web/login
                        )

                    [identityCookie] => 
                    [authTimeout] => 
                    [autoRenewCookie] => 
                    [autoUpdateFlash] => 1
                    [loginRequiredAjaxResponse] => 
                    [_keyPrefix:CWebUser:private] => 2834b10ce4cbd5133226f4bbb6cb3fef
                    [_access:CWebUser:private] => Array
                        (
                        )

                    [behaviors] => Array
                        (
                        )

                    [_initialized:CApplicationComponent:private] => 1
                    [_e:CComponent:private] => 
                    [_m:CComponent:private] => 
                )

            [code] => 500
            [type] => PHP notice
            [message] => Trying to get property of non-object
            [file] => /opt/dreamfactory/platform/vendor/dreamfactory/lib-php-common-platform/src/Utility/Drupal.php
            [line] => 146
            [trace] => #0 /opt/dreamfactory/platform/vendor/dreamfactory/lib-php-common-platform/src/Services/SystemManager.php(796): registerPlatform()
#1 /opt/dreamfactory/platform/app/controllers/WebController.php(546): registerPlatform()
#2 /opt/dreamfactory/platform/app/controllers/WebController.php(1254): WebController->actionWelcome()
#3 /opt/dreamfactory/platform/app/controllers/WebController.php(1207): WebController->_handleAction()
#4 /opt/dreamfactory/platform/app/controllers/WebController.php(185): WebController->_checkSystemState()
#5 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(3911): WebController->actionIndex()
#6 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(3423): CInlineAction->runWithParams()
#7 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(6425): WebController->runAction()
#8 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(6434): CFilterChain->run()
#9 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(3801): CAccessControlFilter->filter()
#10 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(6467): WebController->filterAccessControl()
#11 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(6422): CInlineFilter->filter()
#12 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(3413): CFilterChain->run()
#13 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(3398): WebController->runActionWithFilters()
#14 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(1745): WebController->run()
#15 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(1665): DreamFactory\Platform\Yii\Components\PlatformWebApplication->runController()
#16 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(1190): DreamFactory\Platform\Yii\Components\PlatformWebApplication->processRequest()
#17 /opt/dreamfactory/platform/vendor/dreamfactory/lib-php-common-yii/src/Utility/Pii.php(219): DreamFactory\Platform\Yii\Components\PlatformWebApplication->run()
#18 /opt/dreamfactory/platform/web/index.php(69): run()
```

**Comment by DigNZ** [comment]
I've tried on two different servers, one runs nothing else but a basic LAMP install before following that build.  The other is established and is running development builds of a number of PHP frameworks without issue.

**Comment by jstablesdf** [comment]
What version of CentOS have you installed in? Is anything logged in the DreamFactory installer log and error log(s)?
