### ISSUE TITLE
dreamfactory-1.9.1-1 Upgrade fails on Windows

### ISSUE THREAD

**Issue by ezothner** [dreamfactorysoftware/dsp-core#75]
Trying to use on Windows - first time - forces and Upgrade and fails.  Very bad first time experience for me.

CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1005 Can't create table 'bitnami_dreamfactory.#sql-1b24_d' (errno: 121)

Array
(
    [_viewFile_] => C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\app\views\web\error.php
    [_data_] => Array
        (
            [current_user] => CWebUser Object
                (
                    [allowAutoLogin] => 1
                    [guestName] => Guest
                    [loginUrl] => Array
                        (
                            [0] => web/login
                        )

                    [identityCookie] => 
                    [authTimeout] => 
                    [autoRenewCookie] => 
                    [autoUpdateFlash] => 1
                    [loginRequiredAjaxResponse] => 
                    [_keyPrefix:CWebUser:private] => ee967f0ca36f82227995c1a5bdf811f7
                    [_access:CWebUser:private] => Array
                        (
                        )

                    [behaviors] => Array
                        (
                        )

                    [_initialized:CApplicationComponent:private] => 1
                    [_e:CComponent:private] => 
                    [_m:CComponent:private] => 
                )

            [code] => 500
            [type] => CDbException
            [errorCode] => 0
            [message] => CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1005 Can't create table 'bitnami_dreamfactory.#sql-1b24_d' (errno: 121)
            [file] => C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\yii\framework\yiilite.php
            [line] => 9351
            [trace] => #0 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\yii\framework\yiilite.php(9819): CDbCommand->execute()
#1 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\lib-php-common-platform\src\Utility\SqlDbUtilities.php(1757): CDbCommand->addForeignKey('fk_df_sys_event...', 'df_sys_event', 'created_by_id', 'df_sys_user', 'id', NULL, NULL)
#2 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\lib-php-common-platform\src\Utility\SqlDbUtilities.php(856): DreamFactory\Platform\Utility\SqlDbUtilities::createFieldExtras(Object(CDbConnection), Array)
#3 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\lib-php-common-platform\src\Services\SystemManager.php(295): DreamFactory\Platform\Utility\SqlDbUtilities::updateTables(NULL, Object(CDbConnection), Array, true)
#4 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\app\controllers\WebController.php(250): DreamFactory\Platform\Services\SystemManager::upgradeSchema()
#5 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\app\controllers\WebController.php(1231): WebController->actionUpgradeSchema()
#6 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\app\controllers\WebController.php(1207): WebController->_handleAction(4)
#7 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\app\controllers\WebController.php(185): WebController->_checkSystemState()
#8 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\yii\framework\yiilite.php(3911): WebController->actionIndex()
#9 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\yii\framework\yiilite.php(3423): CInlineAction->runWithParams(Array)
#10 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\yii\framework\yiilite.php(3408): CController->runAction(Object(CInlineAction))
#11 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\yii\framework\yiilite.php(3398): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\yii\framework\yiilite.php(1745): CController->run('')
#13 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\yii\framework\yiilite.php(1665): CWebApplication->runController('')
#14 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\yii\framework\yiilite.php(1190): CWebApplication->processRequest()
#15 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\vendor\dreamfactory\lib-php-common-yii\src\Utility\Pii.php(219): CApplication->run()
#16 C:\Bitnami\dreamfactory-1.9.1-1\apps\dreamfactory\htdocs\web\index.php(69): DreamFactory\Yii\Utility\Pii::run('C:\\Bitnami\\drea...', Object(Composer\Autoload\ClassLoader), 'DreamFactory\\Pl...')
#17 {main}

**Comment by jstablesdf** [comment]
Was your DSP running fine previous to the upgrade? (I.e., able to login to admin console, services configured, API calls made successfully.)
